package fnjsw.entity;

import java.util.Date;

public class Onechildarchives {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.id
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.fName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String fname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.fIdCardNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String fidcardno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.fPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String fphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.marriageIdNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String marriageidno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.fPermanentAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String fpermanentaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.fpHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String fphouseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.fAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String faddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.faHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String fahouseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.fCompanyName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String fcompanyname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.fCompanyAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String fcompanyaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.mName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String mname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.mIdCardNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String midcardno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.mPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String mphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.mPermanentAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String mpermanentaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.mpHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String mphouseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.mAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String maddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.maHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String mahouseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.mCompanyName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String mcompanyname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.mCompanyAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String mcompanyaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.maritalStatus
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String maritalstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.marriageNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String marriageno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.marriageDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private Date marriagedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.hasChild
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String haschild;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.isAdopted
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String isadopted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.residenceNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String residenceno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.getResidenceDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String getresidencedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.registrationAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String registrationaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.serviceNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String serviceno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.registrationDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private Date registrationdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.operator
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.opPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String opphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.status
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.familyPlanningCertificate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String familyplanningcertificate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.zhunShengZheng
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String zhunshengzheng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column onechildarchives.comment
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.id
	 * @return  the value of onechildarchives.id
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.id
	 * @param id  the value for onechildarchives.id
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.fName
	 * @return  the value of onechildarchives.fName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.fName
	 * @param fname  the value for onechildarchives.fName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFname(String fname) {
		this.fname = fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.fIdCardNo
	 * @return  the value of onechildarchives.fIdCardNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFidcardno() {
		return fidcardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.fIdCardNo
	 * @param fidcardno  the value for onechildarchives.fIdCardNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFidcardno(String fidcardno) {
		this.fidcardno = fidcardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.fPhone
	 * @return  the value of onechildarchives.fPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFphone() {
		return fphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.fPhone
	 * @param fphone  the value for onechildarchives.fPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.marriageIdNo
	 * @return  the value of onechildarchives.marriageIdNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMarriageidno() {
		return marriageidno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.marriageIdNo
	 * @param marriageidno  the value for onechildarchives.marriageIdNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMarriageidno(String marriageidno) {
		this.marriageidno = marriageidno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.fPermanentAddress
	 * @return  the value of onechildarchives.fPermanentAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFpermanentaddress() {
		return fpermanentaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.fPermanentAddress
	 * @param fpermanentaddress  the value for onechildarchives.fPermanentAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFpermanentaddress(String fpermanentaddress) {
		this.fpermanentaddress = fpermanentaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.fpHouseNo
	 * @return  the value of onechildarchives.fpHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFphouseno() {
		return fphouseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.fpHouseNo
	 * @param fphouseno  the value for onechildarchives.fpHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFphouseno(String fphouseno) {
		this.fphouseno = fphouseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.fAddress
	 * @return  the value of onechildarchives.fAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFaddress() {
		return faddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.fAddress
	 * @param faddress  the value for onechildarchives.fAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.faHouseNo
	 * @return  the value of onechildarchives.faHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFahouseno() {
		return fahouseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.faHouseNo
	 * @param fahouseno  the value for onechildarchives.faHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFahouseno(String fahouseno) {
		this.fahouseno = fahouseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.fCompanyName
	 * @return  the value of onechildarchives.fCompanyName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFcompanyname() {
		return fcompanyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.fCompanyName
	 * @param fcompanyname  the value for onechildarchives.fCompanyName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFcompanyname(String fcompanyname) {
		this.fcompanyname = fcompanyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.fCompanyAddr
	 * @return  the value of onechildarchives.fCompanyAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFcompanyaddr() {
		return fcompanyaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.fCompanyAddr
	 * @param fcompanyaddr  the value for onechildarchives.fCompanyAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFcompanyaddr(String fcompanyaddr) {
		this.fcompanyaddr = fcompanyaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.mName
	 * @return  the value of onechildarchives.mName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMname() {
		return mname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.mName
	 * @param mname  the value for onechildarchives.mName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMname(String mname) {
		this.mname = mname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.mIdCardNo
	 * @return  the value of onechildarchives.mIdCardNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMidcardno() {
		return midcardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.mIdCardNo
	 * @param midcardno  the value for onechildarchives.mIdCardNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMidcardno(String midcardno) {
		this.midcardno = midcardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.mPhone
	 * @return  the value of onechildarchives.mPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMphone() {
		return mphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.mPhone
	 * @param mphone  the value for onechildarchives.mPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.mPermanentAddress
	 * @return  the value of onechildarchives.mPermanentAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMpermanentaddress() {
		return mpermanentaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.mPermanentAddress
	 * @param mpermanentaddress  the value for onechildarchives.mPermanentAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMpermanentaddress(String mpermanentaddress) {
		this.mpermanentaddress = mpermanentaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.mpHouseNo
	 * @return  the value of onechildarchives.mpHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMphouseno() {
		return mphouseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.mpHouseNo
	 * @param mphouseno  the value for onechildarchives.mpHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMphouseno(String mphouseno) {
		this.mphouseno = mphouseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.mAddress
	 * @return  the value of onechildarchives.mAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMaddress() {
		return maddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.mAddress
	 * @param maddress  the value for onechildarchives.mAddress
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMaddress(String maddress) {
		this.maddress = maddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.maHouseNo
	 * @return  the value of onechildarchives.maHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMahouseno() {
		return mahouseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.maHouseNo
	 * @param mahouseno  the value for onechildarchives.maHouseNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMahouseno(String mahouseno) {
		this.mahouseno = mahouseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.mCompanyName
	 * @return  the value of onechildarchives.mCompanyName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMcompanyname() {
		return mcompanyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.mCompanyName
	 * @param mcompanyname  the value for onechildarchives.mCompanyName
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMcompanyname(String mcompanyname) {
		this.mcompanyname = mcompanyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.mCompanyAddr
	 * @return  the value of onechildarchives.mCompanyAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMcompanyaddr() {
		return mcompanyaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.mCompanyAddr
	 * @param mcompanyaddr  the value for onechildarchives.mCompanyAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMcompanyaddr(String mcompanyaddr) {
		this.mcompanyaddr = mcompanyaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.maritalStatus
	 * @return  the value of onechildarchives.maritalStatus
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMaritalstatus() {
		return maritalstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.maritalStatus
	 * @param maritalstatus  the value for onechildarchives.maritalStatus
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMaritalstatus(String maritalstatus) {
		this.maritalstatus = maritalstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.marriageNo
	 * @return  the value of onechildarchives.marriageNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getMarriageno() {
		return marriageno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.marriageNo
	 * @param marriageno  the value for onechildarchives.marriageNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMarriageno(String marriageno) {
		this.marriageno = marriageno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.marriageDate
	 * @return  the value of onechildarchives.marriageDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public Date getMarriagedate() {
		return marriagedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.marriageDate
	 * @param marriagedate  the value for onechildarchives.marriageDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setMarriagedate(Date marriagedate) {
		this.marriagedate = marriagedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.hasChild
	 * @return  the value of onechildarchives.hasChild
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getHaschild() {
		return haschild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.hasChild
	 * @param haschild  the value for onechildarchives.hasChild
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setHaschild(String haschild) {
		this.haschild = haschild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.isAdopted
	 * @return  the value of onechildarchives.isAdopted
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getIsadopted() {
		return isadopted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.isAdopted
	 * @param isadopted  the value for onechildarchives.isAdopted
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setIsadopted(String isadopted) {
		this.isadopted = isadopted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.residenceNo
	 * @return  the value of onechildarchives.residenceNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getResidenceno() {
		return residenceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.residenceNo
	 * @param residenceno  the value for onechildarchives.residenceNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setResidenceno(String residenceno) {
		this.residenceno = residenceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.getResidenceDate
	 * @return  the value of onechildarchives.getResidenceDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getGetresidencedate() {
		return getresidencedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.getResidenceDate
	 * @param getresidencedate  the value for onechildarchives.getResidenceDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setGetresidencedate(String getresidencedate) {
		this.getresidencedate = getresidencedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.registrationAddr
	 * @return  the value of onechildarchives.registrationAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getRegistrationaddr() {
		return registrationaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.registrationAddr
	 * @param registrationaddr  the value for onechildarchives.registrationAddr
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setRegistrationaddr(String registrationaddr) {
		this.registrationaddr = registrationaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.serviceNo
	 * @return  the value of onechildarchives.serviceNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getServiceno() {
		return serviceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.serviceNo
	 * @param serviceno  the value for onechildarchives.serviceNo
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setServiceno(String serviceno) {
		this.serviceno = serviceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.registrationDate
	 * @return  the value of onechildarchives.registrationDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public Date getRegistrationdate() {
		return registrationdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.registrationDate
	 * @param registrationdate  the value for onechildarchives.registrationDate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setRegistrationdate(Date registrationdate) {
		this.registrationdate = registrationdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.operator
	 * @return  the value of onechildarchives.operator
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.operator
	 * @param operator  the value for onechildarchives.operator
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.opPhone
	 * @return  the value of onechildarchives.opPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getOpphone() {
		return opphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.opPhone
	 * @param opphone  the value for onechildarchives.opPhone
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setOpphone(String opphone) {
		this.opphone = opphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.status
	 * @return  the value of onechildarchives.status
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.status
	 * @param status  the value for onechildarchives.status
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.familyPlanningCertificate
	 * @return  the value of onechildarchives.familyPlanningCertificate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getFamilyplanningcertificate() {
		return familyplanningcertificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.familyPlanningCertificate
	 * @param familyplanningcertificate  the value for onechildarchives.familyPlanningCertificate
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setFamilyplanningcertificate(String familyplanningcertificate) {
		this.familyplanningcertificate = familyplanningcertificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.zhunShengZheng
	 * @return  the value of onechildarchives.zhunShengZheng
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getZhunshengzheng() {
		return zhunshengzheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.zhunShengZheng
	 * @param zhunshengzheng  the value for onechildarchives.zhunShengZheng
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setZhunshengzheng(String zhunshengzheng) {
		this.zhunshengzheng = zhunshengzheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column onechildarchives.comment
	 * @return  the value of onechildarchives.comment
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column onechildarchives.comment
	 * @param comment  the value for onechildarchives.comment
	 * @mbggenerated  Mon Oct 13 22:45:31 CST 2014
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}