CREATE TABLE `onechildarchives` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fName` varchar(255) DEFAULT NULL COMMENT '姓名',
  `fIdCardNo` varchar(255) DEFAULT NULL COMMENT '身份证号',
  `fPhone` varchar(255) DEFAULT NULL COMMENT '联系电话',
  `marriageIdNo` varchar(255) DEFAULT NULL COMMENT '婚育证明号码',
  `fPermanentAddress` varchar(255) DEFAULT NULL COMMENT '户籍地址',
  `fpHouseNo` varchar(255) DEFAULT NULL COMMENT '户籍地址门牌号',
  `fAddress` varchar(255) DEFAULT NULL COMMENT '现居住地址',
  `faHouseNo` varchar(255) DEFAULT NULL COMMENT '户籍地址',
  `fCompanyName` varchar(255) DEFAULT NULL COMMENT '工作单位名称',
  `fCompanyAddr` varchar(255) DEFAULT NULL COMMENT '工作单位地址',
  `mName` varchar(255) DEFAULT NULL COMMENT '门牌号',
  `mIdCardNo` varchar(255) DEFAULT NULL COMMENT '身份证号',
  `mPhone` varchar(255) DEFAULT NULL COMMENT 'mPhone',
  `mPermanentAddress` varchar(2) DEFAULT NULL COMMENT '户籍地址',
  `mpHouseNo` varchar(255) DEFAULT NULL COMMENT '户籍地址门牌号',
  `mAddress` varchar(255) DEFAULT NULL COMMENT '现居住地址',
  `maHouseNo` varchar(255) DEFAULT NULL COMMENT '现居住地址门牌号',
  `mCompanyName` varchar(255) DEFAULT NULL COMMENT '工作单位名称',
  `mCompanyAddr` varchar(255) DEFAULT NULL COMMENT '工作单位地址',
  `maritalStatus` varchar(2) DEFAULT '2' COMMENT '婚姻状况',
  `marriageNo` varchar(255) DEFAULT NULL COMMENT '结婚证号',
  `marriageDate` date DEFAULT NULL COMMENT '结婚时间',
  `hasChild` varchar(2) DEFAULT '2' COMMENT '生育子女状况',
  `isAdopted` varchar(2) DEFAULT '2' COMMENT '是否领养',
  `residenceNo` varchar(255) DEFAULT NULL COMMENT '居住证号',
  `getResidenceDate` varchar(255) DEFAULT NULL COMMENT '领取居住证时间',
  `registrationAddr` varchar(255) DEFAULT NULL COMMENT '办证地点',
  `serviceNo` varchar(255) DEFAULT NULL COMMENT '服务证号',
  `registrationDate` date DEFAULT NULL COMMENT '办证时间',
  `operator` varchar(255) DEFAULT NULL COMMENT '经办人',
  `opPhone` varchar(255) DEFAULT NULL COMMENT '联系电话',
  `status` varchar(2) DEFAULT '1' COMMENT '状态',
  `familyPlanningCertificate` text COMMENT '计生证件扫描文件名',
  `zhunShengZheng` text COMMENT '准生证扫描文件名',
  `comment` text COMMENT '备注',
  `lastServiceTime` date DEFAULT NULL,
  `lastServiceResult` varchar(45) DEFAULT NULL,
  `lastServicePerson` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8

